name: Build drcom-cli
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  x86_64-unknown-linux-gnu:
    name: Build drcom-cli for x86_64-unknown-linux-gnu
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: release to github
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TK }}
