name: Build drcom-cli
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  x86_64-unknown-linux-gnu:
    name: Build drcom-cli for x86_64-unknown-linux-gnu
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: release to github
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: target/release/drcom-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TK }}
  x86_64-pc-windows-msvc:
    name: Build drcom-cli for x86_64-pc-windows-msvc
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: release to github
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: target/release/drcom-cli.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TK }}
  aarch64-unknown-linux-gnu:
    name: build drcom-cli for aarch64-unknown-linux-gnu
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-gnu --release
      - name: rename binary
        run: mv target/aarch64-unknown-linux-gnu/release/drcom-cli{,.aarch64}
      - name: release to github
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: target/aarch64-unknown-linux-gnu/release/drcom-cli.aarch64
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TK }}
